### ISSUE TITLE
Redownloading theme song files. 

### ISSUE THREAD

**Issue by DirgoSalga** [danieladov/jellyfin-plugin-themesongs#10]
I'm having trouble redownloading a theme song that was working. I deleted all the files for this show because I got new video files. I accidentally also deleted the theme song audio file. Now it won't download again. Does the plug in remember that it already downloaded a file for this show? Or does it check every time?

Thank you!

**Comment by danieladov** [comment]
Hi, the plugin only downloads theme songs for tv shows that don't have one. If you scan the library, jellyfin should notice that the mp3 is gone and mark it as a tv show without a theme song.
