### ISSUE TITLE
Jellyfin Android Mobile App loses connectivity when a theme song is played

### ISSUE THREAD

**Issue by axeldna** [danieladov/jellyfin-plugin-themesongs#17]
Hi,

I'm running version 10.7.7 of Jellyfin in Docker in a NAS server and version 10.7.0.2 of the plugin, with the TVDB plugin working fine.
The theme songs were already downloaded to the folder of each show/movie.

When browsing any of the shows/movies in my library using the Android Mobile App, the theme song plays and then suddenly, the app loses connectivity to the server (even though the theme song is still playing) and can't reconnect.

I have to force-close the app to stop the audio playing and reconnect automatically to the server.

Why could this be happening?

**Comment by danieladov** [comment]
This plugin only downloads the songs, the implementation of the playback of the songs is done by the clients.

You should open the issue [here](https://github.com/jellyfin/jellyfin-android/issues/new?assignees=&labels=bug&template=bug-report.yaml)
