### ISSUE TITLE
Store MP3s in Jellyfin's metadata folder instead of the series folder?

### ISSUE THREAD

**Issue by trevholland** [danieladov/jellyfin-plugin-themesongs#19]
Would it be possible to store the themes songs in the Metadata folder instead of inside the series folder?

A lot of people will have the shows stored on spinning hard disks and the metadata on an SSD/NVMe drive. Doing this ensures that no hard drives need to spin up when browsing Jellyfin.

When using this plugin, however, those hard drives have to spin up in order to play the MP3 file. Not only does this cause excess wear and tear on hard drives, it also causes the theme songs to take a long time to start playing since Jellyfin is waiting to read from the disk

It would be great to provide a way to store the MP3s inside Jellyfin's Metadata folder so that the songs can play faster and hard drives don't need to spin just to browse!

Thanks!

**Comment by danieladov** [comment]
Currently, Jellyfin only detects theme songs stored along with the video files, you might want to request that feature at https://features.jellyfin.org/

**Comment by trevholland** [comment]
Sounds good. Thanks!
