### ISSUE TITLE
Songs download correctly (which is technically all the plugin says it does)

### ISSUE THREAD

**Issue by BentIguana** [danieladov/jellyfin-plugin-themesongs#2]
My real issue is the songs not playing. I can manually put videos in /backdrops/video1."file-extension"  , but it breaks the show completely. Attempting to do music the same way yields no result, no matter the title or directory. The setting for theme songs IS on, so is there more I need to do or something I am missing as to why theme songs don't play?

**Comment by danieladov** [comment]
Playing theme songs is currently broken but a fix has been added to master and will be available in the next version.

**Comment by BentIguana** [comment]
Thanks for the info, I'll delete this issue after the update comes out so those looking for the same info as me can see it until then.
