### ISSUE TITLE
Very loud volume and no way to control it

### ISSUE THREAD

**Issue by DrConflict** [danieladov/jellyfin-plugin-themesongs#20]
This is a great plugin but currently it's very loud compared to the media I and I assume many others use. Having a volume setting/control somewhere would be a nice addition.

**Comment by zeroquinc** [comment]
+1

**Comment by danieladov** [comment]
This plugin doesn't implement the funcionality of playing the songs, it just download them. You should request that in [Jellyfin's feature request page](https://features.jellyfin.org/)

**Comment by danieladov** [comment]
You can upvote this feature here https://features.jellyfin.org/posts/1749/volume-setting-for-theme-songs
