### ISSUE TITLE
Theme song is x10 louder than all other audio

### ISSUE THREAD

**Issue by hugo-id** [danieladov/jellyfin-plugin-themesongs#22]
Love your plugin, it works basically flawlessly

But could you please add a volume setting to your plugin?

It doesn't need to be anything fancier than a % slider in the plugins menu, and I would be 1 happy camper

Thanks

**Comment by jozlod** [comment]
Confirmed, this happens for me as well.
Maybe not 10x louder, but about double what it needs to be.
I end up turning down the amp while picking an episode, just to have to turn it up again once we play an episode.

**Comment by alscaldas** [comment]
Do we have any solution to this yet? It would be perfect if the theme song volume would be at the same level as the video itself.

**Comment by jozlod** [comment]
> Do we have any solution to this yet? It would be perfect if the theme song volume would be at the same level as the video itself.

I haven't had any problems with it for awhile.  From a quick look, it looks like the theme songs are getting downloaded are lower volume now. I was running an mp3gain app to check and bulk update the theme songs, but it seems like somethinng has changed. It could be that theTVDB is serving up quieter mp3s now, I'm not sure as I haven't done much testing at all.

**Comment by traptegies** [comment]
Facing the same issue, I created a simple python script to make the theme songs more atmospheric. I am not savvy enough to create a pull request in this project, but maybe it helps or inspires someone else:
https://github.com/traptegies/atmosphere_adjuster/tree/main

**Comment by LiamKarlMitchell** [comment]
Please add a volume setting for the theme song playback or a way to mute it in the interface.

**Comment by danieladov** [comment]
Hi, this plugin only downloads the theme songs, the actual implementation of playing them is in jellyfin. Please, open a an issue on [https://github.com/jellyfin/jellyfin/issues](https://github.com/jellyfin/jellyfin/issues) or create a feature request on [https://features.jellyfin.org/](https://features.jellyfin.org/)

**Comment by LiamKarlMitchell** [comment]
Seems like there is already a request for this as a feature for JellyFin https://features.jellyfin.org/posts/1749/volume-setting-for-theme-songs
