### ISSUE TITLE
Theme song cuts off mid playing

### ISSUE THREAD

**Issue by maplepy** [danieladov/jellyfin-plugin-themesongs#25]

**Comment by danieladov** [comment]
Thats probably because theme songs from plex last 30 seconds maximum

**Comment by maplepy** [comment]
sadge :( no way of having a longer one?

**Comment by maplepy** [comment]
cos just when i'm dancing and singing it cuts off and i see my ugly ass face in the monitor

**Comment by danieladov** [comment]
The plugin relies on plex database, which has only 30 seconds clips for copyright issues

**Comment by maplepy** [comment]
ooh alr, too bad then
