### ISSUE TITLE
[Bug] Icon hides self after done playing, also not visible on Desktop client (non-Flatkrap, Linux)

### ISSUE THREAD

**Issue by OdinVex** [danieladov/jellyfin-plugin-themesongs#29]
The icon that normally shows in flatkrap versions of the Jellyfin Player is not visible on the non-flatkrap versions (Desktop, Linux). It also immediately hides itself after it is done playing an intro, making it impossible to open the controls for it.

**Comment by danieladov** [comment]
The playing of the theme song is done by jellyfin itself, not by this plugin
