### ISSUE TITLE
soundtracks are downloaded but do not play back

### ISSUE THREAD

**Issue by saveiro** [danieladov/jellyfin-plugin-themesongs#31]
Hello everyone, excellent complement.

The soundtracks are downloaded as "theme.mp3" in the folders but when viewing the content it does not play in the background.

Is there anything else to configure?

Thank you,
Best regards

**Comment by danieladov** [comment]
Hi, double-check that you have theme playback enabled. You can find the option under Display settings

**Comment by saveiro** [comment]
> Hi, double-check that you have theme playback enabled. You can find the option under Display settings

it works on ios and android mobile but not on android tv, is there any way to make it work on android tv? thanks for the answer.

**Comment by funnyangrykid** [comment]
I had the same issue. they downloaded perfectly fine, the option was enabled in Display settings, but they would not play when you're in the Shows Library. going to Game of thrones show would not play the theme.

how I solved it was to just do a Library scan afterwards so it can pick up the new theme audio files. 
hope this helps.
