### ISSUE TITLE
Plugin fails to start

### ISSUE THREAD

**Issue by Uatschitchun** [danieladov/jellyfin-plugin-themesongs#5]
After installing to 10.7 I get this in logs and plugin is state "Malfunctioned":
```
[14:29:22] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Theme Songs 10.7.0
[14:29:23] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.ThemeSongs.ThemeSongsManager
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'Jellyfin.Plugin.ThemeSongs.ThemeSongsManager'
```
Am running jellyfin/jellyfin-unstable docker on linux

**Comment by Uatschitchun** [comment]
Oh, and a question:
I have my media mounted read-only into docker. Where will theme songs will be downloaded then?

**Comment by danieladov** [comment]
That's strange, I just installed and is working fine for me. Did you check that you are installing the correct version?
The plugin will download the song in the tv-show folder so it's necessary to have read permissions

**Comment by Uatschitchun** [comment]
If you take a look at the log you'll see it's 10.7.0, so yes, as there's no newer version, I do think it's the correct one.

You probably meant it's needed to have **write** permissions!? ;)

**Comment by danieladov** [comment]
Sorry, write permissions.
After reinstalling few times I get the same error but the plugin stills works. Does it work for you?

**Comment by danieladov** [comment]
The error should be fixed with the last release
