### ISSUE TITLE
Themesongs Installed, No playback

### ISSUE THREAD

**Issue by rangitoto72** [danieladov/jellyfin-plugin-themesongs#7]
I have installed themesongs (10.7.0.2).
It has downloaded the files to the corresponding folders. (theme.mp3)
Does this NOT auto play the theme songs when i click into the tv series folder ?
 The documentation is very vague, I can not see anywhere in any documentation stating if it does or not ?
( if it does not auto play back, can you update Github advising, as i do see on other forums alot of other people asking the same question)

Never mind, you have to go into User=> Settings => Display, and set playback,So this is only enabled on a per user basis, not a global configuration.

You can close this issue, sorry for the inconvenience.

**Comment by CommanderRedYT** [comment]
I have this enabled, but still no audio plays
